require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - vendor/**/*
    - log/**/*
    - db/schema.rb
    - db/migrate/*
    - db/seeds.rb
    - bin/*
    - config/initializers/**/*
    - config/routes/*