version: '3'
services:
  db:
    image: postgres:14-alpine
    container_name: getninjas_database
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  rails:
    build: .
    container_name: getninjas_application
    working_dir: /getninjas
    command: bin/rails s -b 0.0.0.0
    volumes:
      - .:/getninjas:delegated
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true

volumes:
  db-data:
