version: '3'
services:
  db:
    restart: always
    image: postgres:14-alpine
    container_name: getninjas_database
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

volumes:
  db-data:
